Franklin onboarding journey tutorial code changes
adobe/helix-website pull request #143
Opened 2022-10-28 18:15 UTC by varunmitra

## Description

Code changes for Franklin onboarding journey.
Videos hosted on Dynamic Media
Blocks added:
FAQ
Video Text

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Test URL:
https://main--helix-website--kunwarsaluja.hlx.page/drafts/cashub/tutorial-test

2022-10-28 18:53 UTC, varunmitra commented
@rofe can you please review and approve this PR? This is for the Franklin onboarding tutorial videos created by CAS Hub.
Tagging @3vil3mpir3, @kunwarsaluja

2022-10-29 12:33 UTC, rofe requested changes
Please re-add the `faq` block, it is used in production ;)
https://www.hlx.live/docs/faq

2022-10-29 12:33 UTC, rofe commented on blocks/videotext/videotext.css
> +}
Can you turn the CSS around so it is mobile first and use 600, 900 and 1200 breakpoints? See other blocks for examples:
1. default rules for mobile
2. override rules for tablet and desktop using media queries with `min-width:...`

2022-10-29 12:33 UTC, rofe commented on styles/styles.css
> +main .separator
Make it clear that this is a `.section` rule:
```suggestion
main .section.separator
```

2022-11-01 15:01 UTC, varunmitra commented
Closing this PR in favor of https://github.com/adobe/helix-website/pull/144

2022-11-01 15:01 UTC, closed without merging