Add model-viewer block for the Web Components docs page
adobe/helix-website pull request #459
Opened 2024-01-31 11:27 UTC by bdelacretaz

## Description

This adds a `model-viewer` block for the upcoming Web Components docs page, along with the example 3D viewer component from https://modelviewer.dev/ and a `<lazy-loader>` Web Component to load all of that in the `delayed` phase.

## Related Issue

#457

## How Has This Been Tested?

Besides visual testing, the new code is covered by automated tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) (I'm an Adobe employee)
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2024-02-22 01:19 UTC, dylandepass approved these changes
LGMT

2024-02-22 01:19 UTC, dylandepass commented on tests/blocks/model-viewer/model-viewer.mock.html
> +</div>
nit: extra `</div>`

2024-02-22 07:53 UTC, kptdobe requested changes
I think the web component sample we use should be a project specific element, not something completely unrelated for which the code does not belong to the current project code.

2024-03-28 16:46 UTC, bdelacretaz commented
I'll close this PR and create another one with a web component that does something useful for the website.

2024-03-28 16:46 UTC, closed without merging